### ISSUE TITLE
WHY PYTHON??????

### ISSUE THREAD

**Issue by sefinek24** [WakuWakuPadoru/WuWa_Simple_FPSUnlocker#12]
If it were made in .NET 8 or C++, I would gladly use this tool. Unfortunately, it is made in Python, and I definitely won't use it.

Python is completely unsuitable for making such tools. Most antivirus programs will detect the compiled exe file as a virus because PyInstaller is simply garbage, just like the whole Python ecosystem for skids.

https://www.virustotal.com/gui/file/d88da3d6c2a895d0501e12c26d181ab068b82a2b1a078e28e9117592b8b79642

**Comment by WakuWakuPadoru** [comment]
Nothing too complicated. I use Python at work as a Software Dev so I just used it for this fun little project. There are definitely other languages that can be used instead of Python but since I already know that for this use case, it would work perfectly fine with everything already packed, I opted for this. Not going to say that Python is the best for this, but it works so I didn't think too much about it.

As for PyInstaller, it's one of the better ones for this specific use case. Compared to alternatives like Nuitka which uses a C compiler to pump out an executable file, PyInstaller generally has fewer false positives than Nuitka.
